# ==========================================
# Configuration MySQL
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ftth_eligibilite_db
spring.datasource.username=root
spring.datasource.password=amine123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configuration JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ==========================================
# Configuration Serveur
# ==========================================
server.port=8080
spring.application.name=ftth-eligibilite

# ==========================================
# Configuration Logging
# ==========================================
logging.level.root=INFO
logging.level.com.orange.maroc.fttheligibilite=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==========================================
# Configuration API Orange (EXTERNALISÉE)
# ==========================================
api.base.url=http://10.127.16.23/ftth/search/nearby
api.jwt.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL3N1YnNjcmliZXIiOiJpYW0iLCJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2FwcGxpY2F0aW9ubmFtZSI6IkRlZmF1bHRBcHBsaWNhdGlvbiJ9.3GWUkQdW-rg5ikjwZERUcUKVw4kk6fSffNWjwiVkMx8